# Generated by Django 5.2.8 on 2025-11-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationfile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationjob',
            name='mapping',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='bank_identifier',
            field=models.CharField(choices=[('GENERIC', 'Generic'), ('MAGMA', 'Magma'), ('RSA', 'RSA'), ('ICICI', 'ICICI'), ('Oriental', 'Oriental')], default='GENERIC', max_length=20),
        ),
    ]
